import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('Proxy 详情隐藏 Client UUID 并保留两种协议的分享 URI 复制', async () => {
  const source = (await Promise.all(["components/proxy/ProxyForm.vue","components/proxy/ClientList.vue","components/proxy/ClientDetail.vue","components/proxy/ClientForm.vue","composables/useClientForm.ts"].map(path => readFile(new URL('../src/' + path, import.meta.url), 'utf8')))).join('\n')
  assert.match(source, /v-model="proxyProtocol"/)
  assert.match(source, /proxyProtocol === 'vless'/)
  assert.match(source, /:disabled="proxyFormMode === 'edit'"/)
  assert.match(source, /selectedShare\.protocol === 'vless'/)
	assert.match(source, /copyClientURI\(client\)/)
	assert.match(source, /copyShareURI\(selectedShare\.uri\)/)
	assert.match(source, /selectedShare\.protocol === 'vless' \? 'VLESS' : 'Shadowsocks'/)
  assert.match(source, /<th>已用 \/ 总量<\/th><th>周期<\/th><th>到期时间<\/th><th>最近活动<\/th>/)
	assert.match(source, /showsVLESSClientFields\(selectedProxy\.protocol\).*UDP\/443/)
	assert.doesNotMatch(source, /<th[^>]*>UUID<\/th>/)
	assert.doesNotMatch(source, /uuid_summary/)
	assert.doesNotMatch(source, /selectedShare\.client\.uuid/)
	assert.doesNotMatch(source, /复制 UUID/)
  assert.match(source, /本周期上行/)
  assert.match(source, /本周期下行/)
  assert.match(source, /本周期已用/)
  assert.match(source, /clientTrafficResetMode === 'weekly'/)
  assert.match(source, /clientTrafficResetMode === 'monthly'/)
  assert.match(source, /resetClientTraffic/)
  assert.match(source, /clientStatusLabel\(client\.status\)/)
  assert.match(source, /用户启用/)
  assert.match(source, /实际可用/)
  assert.match(source, /clientExpirationMode === 'specified'/)
  assert.match(source, /type="datetime-local"/)
  assert.match(source, /expires_at: clientExpirationMode\.value/)
  assert.match(source, /last_activity_at \? formatTime/)
  assert.doesNotMatch(source, /Reality Public Key|REALITY Public Key|reality_public_key|reality_short_id/)
})
