#!/usr/bin/env bash

set -Eeuo pipefail

readonly REPOSITORY="renaissance0721/vps-panel"
readonly RELEASES_BASE="https://github.com/${REPOSITORY}/releases"
readonly BINARY_PATH="/usr/local/bin/vps-panel-agent"
readonly CONFIG_DIR="/etc/vps-panel-agent"
readonly SERVICE_FILE="/etc/systemd/system/vps-panel-agent.service"
readonly SERVICE_NAME="vps-panel-agent.service"

server_url=""
enrollment_token=""
agent_version=""
architecture=""
temporary_dir=""

log() {
  printf '[vps-panel-agent] %s\n' "$*"
}

fail() {
  printf '[vps-panel-agent] Error: %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage: install-agent.sh --server PANEL_URL --token ENROLLMENT_TOKEN [--version VERSION]

Options:
  --server URL   Public URL of the VPS Panel.
  --token TOKEN  One-time enrollment token generated by the Panel.
  --version TAG  Download Agent assets from this release tag.
  -h, --help     Show this help message.
EOF
}

cleanup() {
  if [[ -n "$temporary_dir" && -d "$temporary_dir" ]]; then
    rm -rf -- "$temporary_dir"
  fi
}

detect_architecture() {
  case "$(uname -m)" in
    x86_64 | amd64) architecture="amd64" ;;
    aarch64 | arm64) architecture="arm64" ;;
    *) fail "unsupported architecture: $(uname -m); only amd64 and arm64 are supported" ;;
  esac
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --server)
      [[ $# -ge 2 ]] || fail "--server requires a value"
      server_url="$2"
      shift 2
      ;;
    --token)
      [[ $# -ge 2 ]] || fail "--token requires a value"
      enrollment_token="$2"
      shift 2
      ;;
    --version)
      [[ $# -ge 2 ]] || fail "--version requires a value"
      agent_version="$2"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *) fail "unknown argument: $1" ;;
  esac
done

[[ ${EUID} -eq 0 ]] || fail "run this installer as root"
[[ "$server_url" =~ ^https?://[^[:space:]]+$ ]] || fail "--server must be an HTTP or HTTPS URL"
[[ -n "$enrollment_token" && "$enrollment_token" != *[[:space:]]* ]] || \
  fail "--token must be a non-empty enrollment token"
if [[ -n "$agent_version" && ! "$agent_version" =~ ^v[0-9][0-9A-Za-z._-]*$ ]]; then
  fail "--version must be a valid release tag"
fi
server_url="${server_url%/}"

for command_name in curl uname systemctl install mktemp chmod; do
  command -v "$command_name" >/dev/null 2>&1 || fail "required command not found: ${command_name}"
done
[[ -d /run/systemd/system ]] || fail "systemd is not running on this VPS"

detect_architecture
temporary_dir="$(mktemp -d)"
trap cleanup EXIT

asset_name="vps-panel-agent-linux-${architecture}"
download_path="${temporary_dir}/${asset_name}"
unit_path="${temporary_dir}/vps-panel-agent.service"

if [[ -n "$agent_version" ]]; then
  download_base="${RELEASES_BASE}/download/${agent_version}"
  log "Downloading ${asset_name} from GitHub Release ${agent_version}..."
else
  download_base="${RELEASES_BASE}/latest/download"
  log "Downloading ${asset_name} from the latest GitHub Release..."
fi
curl --proto '=https' --tlsv1.2 -fL --retry 3 --retry-delay 2 \
  "${download_base}/${asset_name}" \
  -o "$download_path"

chmod 0755 "$download_path"
install -d -m 0700 "$CONFIG_DIR"

cat >"$unit_path" <<EOF
[Unit]
Description=VPS Panel Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${BINARY_PATH}
Restart=on-failure
RestartSec=3
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=strict

[Install]
WantedBy=multi-user.target
EOF
log "Registering Agent..."
"$download_path" register --server "$server_url" --token "$enrollment_token"
enrollment_token=""

install -d -m 0755 /usr/local/bin
install -m 0755 "$download_path" "$BINARY_PATH"
install -m 0644 "$unit_path" "$SERVICE_FILE"

systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
systemctl restart "$SERVICE_NAME"
if ! systemctl is-active --quiet "$SERVICE_NAME"; then
  systemctl status "$SERVICE_NAME" --no-pager >&2 || true
  fail "Agent service did not start"
fi

log "Installation complete. Agent service is running."
