#!/bin/sh

set -eu

REPOSITORY="renaissance0721/vps-panel"
RELEASES_BASE="https://github.com/${REPOSITORY}/releases"
AGENT_DIR="/opt/vps-panel/agent"
BINARY_PATH="${AGENT_DIR}/vps-panel-agent"
CONFIG_DIR="/etc/vps-panel-agent"
SERVICE_NAME="vps-panel-agent"

server_url=""
enrollment_token=""
agent_version=""
architecture=""
temporary_dir=""
init_system=""
service_file=""

log() {
  printf '[vps-panel-agent] %s\n' "$*"
}

fail() {
  printf '[vps-panel-agent] Error: %s\n' "$*" >&2
  exit 1
}

usage() {
  printf '%s\n' \
    'Usage: install-agent.sh --server PANEL_URL --token ENROLLMENT_TOKEN [--version VERSION]' \
    '' \
    'Options:' \
    '  --server URL   Public URL of the VPS Panel.' \
    '  --token TOKEN  One-time enrollment token generated by the Panel.' \
    '  --version TAG  Download Agent assets from this release tag.' \
    '  -h, --help     Show this help message.'
}

cleanup() {
  if [ -n "$temporary_dir" ] && [ -d "$temporary_dir" ]; then
    rm -rf "$temporary_dir"
  fi
}

detect_architecture() {
  case "$(uname -m)" in
    x86_64 | amd64) architecture="amd64" ;;
    aarch64 | arm64) architecture="arm64" ;;
    *) fail "unsupported architecture: $(uname -m); only amd64 and arm64 are supported" ;;
  esac
}

prepare_alpine_dependencies() {
  [ -f /etc/alpine-release ] || return 0
  command -v apk >/dev/null 2>&1 || fail "required command not found: apk"
  if ! command -v curl >/dev/null 2>&1 || [ ! -s /etc/ssl/certs/ca-certificates.crt ]; then
    log "Installing Alpine download dependencies..."
    apk add --no-cache curl ca-certificates
  fi
  if ! command -v install >/dev/null 2>&1; then
    log "Installing Alpine file utility dependency..."
    apk add --no-cache coreutils
  fi
}

detect_init_system() {
  if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
    init_system="systemd"
    service_file="/etc/systemd/system/${SERVICE_NAME}.service"
    return
  fi
  if command -v rc-service >/dev/null 2>&1 && command -v rc-update >/dev/null 2>&1 && \
    { [ -d /run/openrc ] || [ -x /sbin/openrc-run ]; }; then
    init_system="openrc"
    service_file="/etc/init.d/${SERVICE_NAME}"
    command -v supervise-daemon >/dev/null 2>&1 || fail "required OpenRC supervisor not found: supervise-daemon"
    return
  fi
  fail "unsupported init system: systemd or OpenRC is required"
}

write_systemd_service() {
  service_path=$1
  cat >"$service_path" <<EOF
[Unit]
Description=VPS Panel Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${BINARY_PATH}
Restart=on-failure
RestartSec=3
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=strict
ReadWritePaths=/opt/vps-panel/agent /opt/vps-panel/xray /etc/vps-panel/xray /opt/vps-panel/realm /etc/vps-panel/realm /etc/systemd/system

[Install]
WantedBy=multi-user.target
EOF
}

write_openrc_service() {
  service_path=$1
  cat >"$service_path" <<EOF
#!/sbin/openrc-run

name="VPS Panel Agent"
description="VPS Panel Agent"
supervisor="supervise-daemon"
command="${BINARY_PATH}"
respawn_delay=3
respawn_max=0
retry="TERM/10/KILL/5"
umask=0077

depend() {
  need net
}
EOF
}

start_service() {
  if [ "$init_system" = "systemd" ]; then
    systemctl daemon-reload
    systemctl enable "${SERVICE_NAME}.service"
    systemctl restart "${SERVICE_NAME}.service"
    if ! systemctl is-active --quiet "${SERVICE_NAME}.service"; then
      systemctl status "${SERVICE_NAME}.service" --no-pager >&2 || true
      fail "Agent service did not start"
    fi
    return
  fi
  rc-update add "$SERVICE_NAME" default
  if rc-service "$SERVICE_NAME" status >/dev/null 2>&1; then
    rc-service "$SERVICE_NAME" restart
  else
    rc-service "$SERVICE_NAME" start
  fi
  rc-service "$SERVICE_NAME" status >/dev/null 2>&1 || fail "Agent OpenRC service did not start"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --server)
      [ "$#" -ge 2 ] || fail "--server requires a value"
      server_url=$2
      shift 2
      ;;
    --token)
      [ "$#" -ge 2 ] || fail "--token requires a value"
      enrollment_token=$2
      shift 2
      ;;
    --version)
      [ "$#" -ge 2 ] || fail "--version requires a value"
      agent_version=$2
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *) fail "unknown argument: $1" ;;
  esac
done

[ "$(id -u)" -eq 0 ] || fail "run this installer as root"
case "$server_url" in
  http://* | https://*) ;;
  *) fail "--server must be an HTTP or HTTPS URL" ;;
esac
case "$server_url" in *[[:space:]]*) fail "--server must not contain whitespace" ;; esac
case "$enrollment_token" in '' | *[[:space:]]*) fail "--token must be a non-empty enrollment token" ;; esac
if [ -n "$agent_version" ]; then
  case "$agent_version" in
    v[0-9]*) ;;
    *) fail "--version must be a valid release tag" ;;
  esac
  case "$agent_version" in *[!0-9A-Za-z._-]*) fail "--version must be a valid release tag" ;; esac
fi
server_url=${server_url%/}

prepare_alpine_dependencies
for command_name in curl uname install mktemp chmod id; do
  command -v "$command_name" >/dev/null 2>&1 || fail "required command not found: ${command_name}"
done
detect_init_system
detect_architecture

temporary_dir=$(mktemp -d)
trap cleanup 0
trap 'exit 1' HUP INT TERM

asset_name="vps-panel-agent-linux-${architecture}"
download_path="${temporary_dir}/${asset_name}"
service_path="${temporary_dir}/${SERVICE_NAME}"

if [ -n "$agent_version" ]; then
  download_base="${RELEASES_BASE}/download/${agent_version}"
  log "Downloading ${asset_name} from GitHub Release ${agent_version}..."
else
  download_base="${RELEASES_BASE}/latest/download"
  log "Downloading ${asset_name} from the latest GitHub Release..."
fi
curl --proto '=https' --tlsv1.2 -fL --retry 3 --retry-delay 2 \
  "${download_base}/${asset_name}" -o "$download_path"

chmod 0755 "$download_path"
install -d -m 0700 "$CONFIG_DIR"
install -d -m 0755 "$AGENT_DIR"
install -d -m 0755 /opt/vps-panel/xray /opt/vps-panel/realm
install -d -m 0700 /etc/vps-panel/xray /etc/vps-panel/realm

if [ "$init_system" = "systemd" ]; then
  write_systemd_service "$service_path"
else
  write_openrc_service "$service_path"
fi

log "Registering Agent..."
"$download_path" register --server "$server_url" --token "$enrollment_token"
enrollment_token=""

install -m 0755 "$download_path" "$BINARY_PATH"
if [ "$init_system" = "systemd" ]; then
  install -m 0644 "$service_path" "$service_file"
else
  install -m 0755 "$service_path" "$service_file"
fi
start_service

log "Installation complete. Agent service is running with ${init_system}."
